# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, nightly ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Cache HaxeLib
        uses: actions/cache@v2
        with:
          path: |
            /tmp/haxelib
          key: HaxelibLin
      # Cache to prevent 30 minute compile time for smallest of changes
      - name: Cache FNFBRBIN
        uses: actions/cache@v2
        with:
          path: |
            /tmp/fnfbrbin
          key: BinLin
      # Runs a set of commands using the runners shell
          
          # haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
      - name: Install Haxelib
        run: |
          haxelib setup /tmp/haxelib
          sh installDeps.bat
        shell: bash
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build linux --app-version="4.3.0-${{ github.run_id}}" -Dghaction
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild
          path: /tmp/fnfbrbin/linux/bin/      
      - name: Publish without changed assets as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild-Minimal
          path: |
                /tmp/fnfbrbin/linux/bin/FNF Super Engine
                /tmp/fnfbrbin/linux/bin/manifest
                /tmp/fnfbrbin/linux/bin/mods/readme.txt
                /tmp/fnfbrbin/linux/bin/mods/docs.md
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Cache HaxeLib
        uses: actions/cache@v2
        with:
          path: |
            C:/haxelib
          key: Haxelib
      # Cache to prevent 30 minute compile time for smallest of changes
      - name: Cache FNFBRBIN
        uses: actions/cache@v2
        with:
          path: |
            C:/fnfbrbin
          key: Bin
      # Runs a set of commands using the runners shell
          
          # haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          installDeps.bat
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.3.0-${{ github.run_id}}" -Dghaction
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: C:/fnfbrbin/windows/bin      
      - name: Publish without changed assets as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild-Minimal
          path: |
                C:/fnfbrbin/windows/bin/FNF Super Engine.exe
                C:/fnfbrbin/windows/bin/manifest
                C:/fnfbrbin/windows/bin/mods/readme.txt
                C:/fnfbrbin/windows/bin/mods/docs.md
